window.MARKET_DATA = {
  "generatedAt": "2026-06-03T00:12:01+00:00",
  "provider": "Alpha Vantage GLOBAL_QUOTE",
  "currencyNote": "O preço é exibido na moeda do instrumento listado.",
  "indicators": {
    "Acura": {
      "brand": "Acura",
      "marketEntity": "Honda Motor Co., Ltd.",
      "displayTicker": "HMC",
      "quoteSymbol": "HMC",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Acura",
      "price": 26.48,
      "change": 0.24,
      "changePercent": 0.9146,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:08:38+00:00",
      "status": "ok"
    },
    "Apollo": {
      "brand": "Apollo",
      "marketEntity": "Apollo Automobil",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Arash": {
      "brand": "Arash",
      "marketEntity": "Arash Motor Company",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Aspark": {
      "brand": "Aspark",
      "marketEntity": "Aspark Co., Ltd.",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Aston Martin": {
      "brand": "Aston Martin",
      "marketEntity": "Aston Martin Lagonda Global Holdings plc",
      "displayTicker": "AML",
      "quoteSymbol": "AML.LON",
      "exchange": "London Stock Exchange",
      "currency": "GBX",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 45.6,
      "change": 0.38,
      "changePercent": 0.8403,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:08:51+00:00",
      "status": "ok"
    },
    "Audi": {
      "brand": "Audi",
      "marketEntity": "Volkswagen AG",
      "displayTicker": "VOW3.DE",
      "quoteSymbol": "VOW3.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: grupo controlador da Audi",
      "price": 91.02,
      "change": 0.46,
      "changePercent": 0.508,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:09:04+00:00",
      "status": "ok"
    },
    "BMW": {
      "brand": "BMW",
      "marketEntity": "Bayerische Motoren Werke AG",
      "displayTicker": "BMW.DE",
      "quoteSymbol": "BMW.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 72.98,
      "change": -0.74,
      "changePercent": -1.0038,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:09:18+00:00",
      "status": "ok"
    },
    "Bizzarrini": {
      "brand": "Bizzarrini",
      "marketEntity": "Bizzarrini",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Brabham": {
      "brand": "Brabham",
      "marketEntity": "Brabham Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Bugatti": {
      "brand": "Bugatti",
      "marketEntity": "Porsche AG",
      "displayTicker": "P911.DE",
      "quoteSymbol": "P911.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_shareholder",
      "relationLabel": "Proxy: acionista relevante da Bugatti Rimac",
      "price": 47.89,
      "change": 0.81,
      "changePercent": 1.7205,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:09:31+00:00",
      "status": "ok"
    },
    "Chevrolet": {
      "brand": "Chevrolet",
      "marketEntity": "General Motors Company",
      "displayTicker": "GM",
      "quoteSymbol": "GM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Chevrolet",
      "price": 81.73,
      "change": -0.95,
      "changePercent": -1.149,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:09:44+00:00",
      "status": "ok"
    },
    "Czinger": {
      "brand": "Czinger",
      "marketEntity": "Czinger Vehicles",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Dallara": {
      "brand": "Dallara",
      "marketEntity": "Dallara Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "De Tomaso": {
      "brand": "De Tomaso",
      "marketEntity": "De Tomaso Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Delage": {
      "brand": "Delage",
      "marketEntity": "Delage Automobiles",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Devel": {
      "brand": "Devel",
      "marketEntity": "Devel Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Donkervoort": {
      "brand": "Donkervoort",
      "marketEntity": "Donkervoort Automobielen",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Fenyr": {
      "brand": "Fenyr",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Ferrari": {
      "brand": "Ferrari",
      "marketEntity": "Ferrari N.V.",
      "displayTicker": "RACE",
      "quoteSymbol": "RACE",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 353.81,
      "change": 4.57,
      "changePercent": 1.3086,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:09:57+00:00",
      "status": "ok"
    },
    "Ford": {
      "brand": "Ford",
      "marketEntity": "Ford Motor Company",
      "displayTicker": "F",
      "quoteSymbol": "F",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 16.15,
      "change": -0.48,
      "changePercent": -2.8863,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:10:10+00:00",
      "status": "ok"
    },
    "Glickenhaus": {
      "brand": "Glickenhaus",
      "marketEntity": "Scuderia Cameron Glickenhaus",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Gordon Murray Automotive": {
      "brand": "Gordon Murray Automotive",
      "marketEntity": "Gordon Murray Group",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Gumpert": {
      "brand": "Gumpert",
      "marketEntity": "Apollo Automobil",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Hennessey": {
      "brand": "Hennessey",
      "marketEntity": "Hennessey Performance Engineering",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Hispanos Suiza": {
      "brand": "Hispanos Suiza",
      "marketEntity": "Hispano Suiza Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Honda": {
      "brand": "Honda",
      "marketEntity": "Honda Motor Co., Ltd.",
      "displayTicker": "HMC",
      "quoteSymbol": "HMC",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 26.48,
      "change": 0.24,
      "changePercent": 0.9146,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:08:38+00:00",
      "status": "ok"
    },
    "Jaguar": {
      "brand": "Jaguar",
      "marketEntity": "Tata Motors Limited",
      "displayTicker": "TATAMOTORS.NS",
      "quoteSymbol": "TATAMOTORS.BSE",
      "exchange": "India",
      "currency": "INR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Jaguar",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "no_quote"
    },
    "Koenigsegg": {
      "brand": "Koenigsegg",
      "marketEntity": "Koenigsegg Automotive AB",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Laffite": {
      "brand": "Laffite",
      "marketEntity": "Laffite Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Lamborghini": {
      "brand": "Lamborghini",
      "marketEntity": "Volkswagen AG",
      "displayTicker": "VOW3.DE",
      "quoteSymbol": "VOW3.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: grupo controlador da Lamborghini",
      "price": 91.02,
      "change": 0.46,
      "changePercent": 0.508,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:09:04+00:00",
      "status": "ok"
    },
    "Lexus": {
      "brand": "Lexus",
      "marketEntity": "Toyota Motor Corporation",
      "displayTicker": "TM",
      "quoteSymbol": "TM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Lexus",
      "price": 180.49,
      "change": -2.43,
      "changePercent": -1.3284,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:10:37+00:00",
      "status": "ok"
    },
    "Lotus": {
      "brand": "Lotus",
      "marketEntity": "Lotus Technology Inc.",
      "displayTicker": "LOT",
      "quoteSymbol": "LOT",
      "exchange": "NASDAQ",
      "currency": "USD",
      "relationType": "proxy_affiliated",
      "relationLabel": "Proxy: empresa listada associada à marca Lotus",
      "price": 1.32,
      "change": -0.01,
      "changePercent": -0.7519,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:10:50+00:00",
      "status": "ok"
    },
    "Lykan": {
      "brand": "Lykan",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Maserati": {
      "brand": "Maserati",
      "marketEntity": "Stellantis N.V.",
      "displayTicker": "STLA",
      "quoteSymbol": "STLA",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Maserati",
      "price": 7.68,
      "change": -0.14,
      "changePercent": -1.7903,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:11:03+00:00",
      "status": "ok"
    },
    "McLaren": {
      "brand": "McLaren",
      "marketEntity": "McLaren Group Holdings",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Mercedes-AMG": {
      "brand": "Mercedes-AMG",
      "marketEntity": "Mercedes-Benz Group AG",
      "displayTicker": "MBG.DE",
      "quoteSymbol": "MBG.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Mercedes-AMG",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "no_quote"
    },
    "Mercedes-Benz": {
      "brand": "Mercedes-Benz",
      "marketEntity": "Mercedes-Benz Group AG",
      "displayTicker": "MBG.DE",
      "quoteSymbol": "MBG.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "no_quote"
    },
    "Mosler": {
      "brand": "Mosler",
      "marketEntity": "Mosler Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Sem cotação pública direta confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "NIO": {
      "brand": "NIO",
      "marketEntity": "NIO Inc.",
      "displayTicker": "NIO",
      "quoteSymbol": "NIO",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 6.01,
      "change": 0.03,
      "changePercent": 0.5017,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:11:32+00:00",
      "status": "ok"
    },
    "Naran": {
      "brand": "Naran",
      "marketEntity": "Naran Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Nilu27": {
      "brand": "Nilu27",
      "marketEntity": "Nilu27",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Nissan": {
      "brand": "Nissan",
      "marketEntity": "Nissan Motor Co., Ltd.",
      "displayTicker": "NSANY",
      "quoteSymbol": "NSANY",
      "exchange": "OTC/ADR",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação ADR da fabricante",
      "price": 4.652,
      "change": -0.058,
      "changePercent": -1.2314,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:11:45+00:00",
      "status": "ok"
    },
    "Noble": {
      "brand": "Noble",
      "marketEntity": "Noble Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Pagani": {
      "brand": "Pagani",
      "marketEntity": "Pagani Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Pininfarina": {
      "brand": "Pininfarina",
      "marketEntity": "Mahindra & Mahindra Ltd.",
      "displayTicker": "M&M.NS",
      "quoteSymbol": "M&M.BSE",
      "exchange": "India",
      "currency": "INR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Pininfarina",
      "price": 2998.7,
      "change": 27.5,
      "changePercent": 0.9256,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:12:01+00:00",
      "status": "ok"
    },
    "Porsche": {
      "brand": "Porsche",
      "marketEntity": "Porsche AG",
      "displayTicker": "P911.DE",
      "quoteSymbol": "P911.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 47.89,
      "change": 0.81,
      "changePercent": 1.7205,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:09:31+00:00",
      "status": "ok"
    },
    "Praga": {
      "brand": "Praga",
      "marketEntity": "Praga Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Red Bull": {
      "brand": "Red Bull",
      "marketEntity": "Red Bull GmbH",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Rimac": {
      "brand": "Rimac",
      "marketEntity": "Rimac Group",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Rodin": {
      "brand": "Rodin",
      "marketEntity": "Rodin Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "SCG": {
      "brand": "SCG",
      "marketEntity": "Scuderia Cameron Glickenhaus",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "SSC": {
      "brand": "SSC",
      "marketEntity": "SSC North America",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Saleen": {
      "brand": "Saleen",
      "marketEntity": "Saleen Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Sem cotação pública direta confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Spyker": {
      "brand": "Spyker",
      "marketEntity": "Spyker",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "unavailable",
      "relationLabel": "Sem indicador de mercado confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "TVR": {
      "brand": "TVR",
      "marketEntity": "TVR",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Toyota": {
      "brand": "Toyota",
      "marketEntity": "Toyota Motor Corporation",
      "displayTicker": "TM",
      "quoteSymbol": "TM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 180.49,
      "change": -2.43,
      "changePercent": -1.3284,
      "latestTradingDay": "2026-06-02",
      "lastUpdated": "2026-06-03T00:10:37+00:00",
      "status": "ok"
    },
    "Tushek": {
      "brand": "Tushek",
      "marketEntity": "Tushek & Spigel Supercars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Ultima": {
      "brand": "Ultima",
      "marketEntity": "Ultima Sports",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Vector": {
      "brand": "Vector",
      "marketEntity": "Vector Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "W Motors": {
      "brand": "W Motors",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Zenvo": {
      "brand": "Zenvo",
      "marketEntity": "Zenvo Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    }
  }
};
