window.MARKET_DATA = {
  "generatedAt": "2026-07-13T23:27:08+00:00",
  "provider": "Alpha Vantage GLOBAL_QUOTE",
  "currencyNote": "O preço é exibido na moeda do instrumento listado.",
  "indicators": {
    "Acura": {
      "brand": "Acura",
      "marketEntity": "Honda Motor Co., Ltd.",
      "displayTicker": "HMC",
      "quoteSymbol": "HMC",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Acura",
      "price": 27.84,
      "change": -0.09,
      "changePercent": -0.3222,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:23:51+00:00",
      "status": "ok"
    },
    "Apollo": {
      "brand": "Apollo",
      "marketEntity": "Apollo Automobil",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Arash": {
      "brand": "Arash",
      "marketEntity": "Arash Motor Company",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Aspark": {
      "brand": "Aspark",
      "marketEntity": "Aspark Co., Ltd.",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Aston Martin": {
      "brand": "Aston Martin",
      "marketEntity": "Aston Martin Lagonda Global Holdings plc",
      "displayTicker": "AML",
      "quoteSymbol": "AML.LON",
      "exchange": "London Stock Exchange",
      "currency": "GBX",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 37.0,
      "change": -0.2,
      "changePercent": -0.5376,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:24:04+00:00",
      "status": "ok"
    },
    "Audi": {
      "brand": "Audi",
      "marketEntity": "Volkswagen AG",
      "displayTicker": "VOW3.DE",
      "quoteSymbol": "VOW3.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: grupo controlador da Audi",
      "price": 71.44,
      "change": 0.46,
      "changePercent": 0.6481,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:24:17+00:00",
      "status": "ok"
    },
    "BMW": {
      "brand": "BMW",
      "marketEntity": "Bayerische Motoren Werke AG",
      "displayTicker": "BMW.DE",
      "quoteSymbol": "BMW.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 57.92,
      "change": -0.22,
      "changePercent": -0.3784,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:24:30+00:00",
      "status": "ok"
    },
    "Bizzarrini": {
      "brand": "Bizzarrini",
      "marketEntity": "Bizzarrini",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Brabham": {
      "brand": "Brabham",
      "marketEntity": "Brabham Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Bugatti": {
      "brand": "Bugatti",
      "marketEntity": "Porsche AG",
      "displayTicker": "P911.DE",
      "quoteSymbol": "P911.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_shareholder",
      "relationLabel": "Proxy: acionista relevante da Bugatti Rimac",
      "price": 44.6,
      "change": -0.53,
      "changePercent": -1.1744,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:24:43+00:00",
      "status": "ok"
    },
    "Chevrolet": {
      "brand": "Chevrolet",
      "marketEntity": "General Motors Company",
      "displayTicker": "GM",
      "quoteSymbol": "GM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Chevrolet",
      "price": 76.72,
      "change": -1.13,
      "changePercent": -1.4515,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:24:56+00:00",
      "status": "ok"
    },
    "Czinger": {
      "brand": "Czinger",
      "marketEntity": "Czinger Vehicles",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Dallara": {
      "brand": "Dallara",
      "marketEntity": "Dallara Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "De Tomaso": {
      "brand": "De Tomaso",
      "marketEntity": "De Tomaso Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Delage": {
      "brand": "Delage",
      "marketEntity": "Delage Automobiles",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Devel": {
      "brand": "Devel",
      "marketEntity": "Devel Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Donkervoort": {
      "brand": "Donkervoort",
      "marketEntity": "Donkervoort Automobielen",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Fenyr": {
      "brand": "Fenyr",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Ferrari": {
      "brand": "Ferrari",
      "marketEntity": "Ferrari N.V.",
      "displayTicker": "RACE",
      "quoteSymbol": "RACE",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 372.98,
      "change": -3.66,
      "changePercent": -0.9718,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:25:09+00:00",
      "status": "ok"
    },
    "Ford": {
      "brand": "Ford",
      "marketEntity": "Ford Motor Company",
      "displayTicker": "F",
      "quoteSymbol": "F",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 13.85,
      "change": -0.15,
      "changePercent": -1.0714,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:25:22+00:00",
      "status": "ok"
    },
    "Glickenhaus": {
      "brand": "Glickenhaus",
      "marketEntity": "Scuderia Cameron Glickenhaus",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Gordon Murray Automotive": {
      "brand": "Gordon Murray Automotive",
      "marketEntity": "Gordon Murray Group",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Gumpert": {
      "brand": "Gumpert",
      "marketEntity": "Apollo Automobil",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Hennessey": {
      "brand": "Hennessey",
      "marketEntity": "Hennessey Performance Engineering",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Hispanos Suiza": {
      "brand": "Hispanos Suiza",
      "marketEntity": "Hispano Suiza Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Honda": {
      "brand": "Honda",
      "marketEntity": "Honda Motor Co., Ltd.",
      "displayTicker": "HMC",
      "quoteSymbol": "HMC",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 27.84,
      "change": -0.09,
      "changePercent": -0.3222,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:23:51+00:00",
      "status": "ok"
    },
    "Jaguar": {
      "brand": "Jaguar",
      "marketEntity": "Tata Motors Limited",
      "displayTicker": "TATAMOTORS.NS",
      "quoteSymbol": "TATAMOTORS.BSE",
      "exchange": "India",
      "currency": "INR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Jaguar",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "no_quote"
    },
    "Koenigsegg": {
      "brand": "Koenigsegg",
      "marketEntity": "Koenigsegg Automotive AB",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Laffite": {
      "brand": "Laffite",
      "marketEntity": "Laffite Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Lamborghini": {
      "brand": "Lamborghini",
      "marketEntity": "Volkswagen AG",
      "displayTicker": "VOW3.DE",
      "quoteSymbol": "VOW3.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: grupo controlador da Lamborghini",
      "price": 71.44,
      "change": 0.46,
      "changePercent": 0.6481,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:24:17+00:00",
      "status": "ok"
    },
    "Lexus": {
      "brand": "Lexus",
      "marketEntity": "Toyota Motor Corporation",
      "displayTicker": "TM",
      "quoteSymbol": "TM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Lexus",
      "price": 174.75,
      "change": -1.7,
      "changePercent": -0.9634,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:25:48+00:00",
      "status": "ok"
    },
    "Lotus": {
      "brand": "Lotus",
      "marketEntity": "Lotus Technology Inc.",
      "displayTicker": "LOT",
      "quoteSymbol": "LOT",
      "exchange": "NASDAQ",
      "currency": "USD",
      "relationType": "proxy_affiliated",
      "relationLabel": "Proxy: empresa listada associada à marca Lotus",
      "price": 1.1,
      "change": -0.045,
      "changePercent": -3.9301,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:26:01+00:00",
      "status": "ok"
    },
    "Lykan": {
      "brand": "Lykan",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Maserati": {
      "brand": "Maserati",
      "marketEntity": "Stellantis N.V.",
      "displayTicker": "STLA",
      "quoteSymbol": "STLA",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Maserati",
      "price": 5.57,
      "change": 0.07,
      "changePercent": 1.2727,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:26:14+00:00",
      "status": "ok"
    },
    "McLaren": {
      "brand": "McLaren",
      "marketEntity": "McLaren Group Holdings",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Mercedes-AMG": {
      "brand": "Mercedes-AMG",
      "marketEntity": "Mercedes-Benz Group AG",
      "displayTicker": "MBG.DE",
      "quoteSymbol": "MBG.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Mercedes-AMG",
      "price": 44.29,
      "change": 0.3,
      "changePercent": 0.682,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:26:27+00:00",
      "status": "ok"
    },
    "Mercedes-Benz": {
      "brand": "Mercedes-Benz",
      "marketEntity": "Mercedes-Benz Group AG",
      "displayTicker": "MBG.DE",
      "quoteSymbol": "MBG.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 44.29,
      "change": 0.3,
      "changePercent": 0.682,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:26:27+00:00",
      "status": "ok"
    },
    "Mosler": {
      "brand": "Mosler",
      "marketEntity": "Mosler Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Sem cotação pública direta confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "NIO": {
      "brand": "NIO",
      "marketEntity": "NIO Inc.",
      "displayTicker": "NIO",
      "quoteSymbol": "NIO",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 4.93,
      "change": 0.15,
      "changePercent": 3.1381,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:26:40+00:00",
      "status": "ok"
    },
    "Naran": {
      "brand": "Naran",
      "marketEntity": "Naran Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Nilu27": {
      "brand": "Nilu27",
      "marketEntity": "Nilu27",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Nissan": {
      "brand": "Nissan",
      "marketEntity": "Nissan Motor Co., Ltd.",
      "displayTicker": "NSANY",
      "quoteSymbol": "NSANY",
      "exchange": "OTC/ADR",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação ADR da fabricante",
      "price": 3.81,
      "change": -0.11,
      "changePercent": -2.8061,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:26:54+00:00",
      "status": "ok"
    },
    "Noble": {
      "brand": "Noble",
      "marketEntity": "Noble Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Pagani": {
      "brand": "Pagani",
      "marketEntity": "Pagani Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Pininfarina": {
      "brand": "Pininfarina",
      "marketEntity": "Mahindra & Mahindra Ltd.",
      "displayTicker": "M&M.NS",
      "quoteSymbol": "M&M.BSE",
      "exchange": "India",
      "currency": "INR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Pininfarina",
      "price": 3159.3501,
      "change": 30.2002,
      "changePercent": 0.9651,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:27:08+00:00",
      "status": "ok"
    },
    "Porsche": {
      "brand": "Porsche",
      "marketEntity": "Porsche AG",
      "displayTicker": "P911.DE",
      "quoteSymbol": "P911.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 44.6,
      "change": -0.53,
      "changePercent": -1.1744,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:24:43+00:00",
      "status": "ok"
    },
    "Praga": {
      "brand": "Praga",
      "marketEntity": "Praga Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Red Bull": {
      "brand": "Red Bull",
      "marketEntity": "Red Bull GmbH",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Rimac": {
      "brand": "Rimac",
      "marketEntity": "Rimac Group",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Rodin": {
      "brand": "Rodin",
      "marketEntity": "Rodin Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "SCG": {
      "brand": "SCG",
      "marketEntity": "Scuderia Cameron Glickenhaus",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "SSC": {
      "brand": "SSC",
      "marketEntity": "SSC North America",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Saleen": {
      "brand": "Saleen",
      "marketEntity": "Saleen Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Sem cotação pública direta confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Spyker": {
      "brand": "Spyker",
      "marketEntity": "Spyker",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "unavailable",
      "relationLabel": "Sem indicador de mercado confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "TVR": {
      "brand": "TVR",
      "marketEntity": "TVR",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Toyota": {
      "brand": "Toyota",
      "marketEntity": "Toyota Motor Corporation",
      "displayTicker": "TM",
      "quoteSymbol": "TM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 174.75,
      "change": -1.7,
      "changePercent": -0.9634,
      "latestTradingDay": "2026-07-13",
      "lastUpdated": "2026-07-13T23:25:48+00:00",
      "status": "ok"
    },
    "Tushek": {
      "brand": "Tushek",
      "marketEntity": "Tushek & Spigel Supercars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Ultima": {
      "brand": "Ultima",
      "marketEntity": "Ultima Sports",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Vector": {
      "brand": "Vector",
      "marketEntity": "Vector Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "W Motors": {
      "brand": "W Motors",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Zenvo": {
      "brand": "Zenvo",
      "marketEntity": "Zenvo Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    }
  }
};
