window.MARKET_DATA = {
  "generatedAt": "2026-06-04T00:14:54+00:00",
  "provider": "Alpha Vantage GLOBAL_QUOTE",
  "currencyNote": "O preço é exibido na moeda do instrumento listado.",
  "indicators": {
    "Acura": {
      "brand": "Acura",
      "marketEntity": "Honda Motor Co., Ltd.",
      "displayTicker": "HMC",
      "quoteSymbol": "HMC",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Acura",
      "price": 27.71,
      "change": 1.23,
      "changePercent": 4.645,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:11:24+00:00",
      "status": "ok"
    },
    "Apollo": {
      "brand": "Apollo",
      "marketEntity": "Apollo Automobil",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Arash": {
      "brand": "Arash",
      "marketEntity": "Arash Motor Company",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Aspark": {
      "brand": "Aspark",
      "marketEntity": "Aspark Co., Ltd.",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Aston Martin": {
      "brand": "Aston Martin",
      "marketEntity": "Aston Martin Lagonda Global Holdings plc",
      "displayTicker": "AML",
      "quoteSymbol": "AML.LON",
      "exchange": "London Stock Exchange",
      "currency": "GBX",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 42.06,
      "change": -3.54,
      "changePercent": -7.7632,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:11:42+00:00",
      "status": "ok"
    },
    "Audi": {
      "brand": "Audi",
      "marketEntity": "Volkswagen AG",
      "displayTicker": "VOW3.DE",
      "quoteSymbol": "VOW3.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: grupo controlador da Audi",
      "price": 89.32,
      "change": -1.7,
      "changePercent": -1.8677,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:11:56+00:00",
      "status": "ok"
    },
    "BMW": {
      "brand": "BMW",
      "marketEntity": "Bayerische Motoren Werke AG",
      "displayTicker": "BMW.DE",
      "quoteSymbol": "BMW.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 71.32,
      "change": -1.66,
      "changePercent": -2.2746,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:12:09+00:00",
      "status": "ok"
    },
    "Bizzarrini": {
      "brand": "Bizzarrini",
      "marketEntity": "Bizzarrini",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Brabham": {
      "brand": "Brabham",
      "marketEntity": "Brabham Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Bugatti": {
      "brand": "Bugatti",
      "marketEntity": "Porsche AG",
      "displayTicker": "P911.DE",
      "quoteSymbol": "P911.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_shareholder",
      "relationLabel": "Proxy: acionista relevante da Bugatti Rimac",
      "price": 47.58,
      "change": -0.31,
      "changePercent": -0.6473,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:12:26+00:00",
      "status": "ok"
    },
    "Chevrolet": {
      "brand": "Chevrolet",
      "marketEntity": "General Motors Company",
      "displayTicker": "GM",
      "quoteSymbol": "GM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Chevrolet",
      "price": 81.7,
      "change": -0.03,
      "changePercent": -0.0367,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:12:39+00:00",
      "status": "ok"
    },
    "Czinger": {
      "brand": "Czinger",
      "marketEntity": "Czinger Vehicles",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Dallara": {
      "brand": "Dallara",
      "marketEntity": "Dallara Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "De Tomaso": {
      "brand": "De Tomaso",
      "marketEntity": "De Tomaso Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Delage": {
      "brand": "Delage",
      "marketEntity": "Delage Automobiles",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Devel": {
      "brand": "Devel",
      "marketEntity": "Devel Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Donkervoort": {
      "brand": "Donkervoort",
      "marketEntity": "Donkervoort Automobielen",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Fenyr": {
      "brand": "Fenyr",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Ferrari": {
      "brand": "Ferrari",
      "marketEntity": "Ferrari N.V.",
      "displayTicker": "RACE",
      "quoteSymbol": "RACE",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 344.4,
      "change": -9.41,
      "changePercent": -2.6596,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:12:52+00:00",
      "status": "ok"
    },
    "Ford": {
      "brand": "Ford",
      "marketEntity": "Ford Motor Company",
      "displayTicker": "F",
      "quoteSymbol": "F",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 15.71,
      "change": -0.44,
      "changePercent": -2.7245,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:13:06+00:00",
      "status": "ok"
    },
    "Glickenhaus": {
      "brand": "Glickenhaus",
      "marketEntity": "Scuderia Cameron Glickenhaus",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Gordon Murray Automotive": {
      "brand": "Gordon Murray Automotive",
      "marketEntity": "Gordon Murray Group",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Gumpert": {
      "brand": "Gumpert",
      "marketEntity": "Apollo Automobil",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Hennessey": {
      "brand": "Hennessey",
      "marketEntity": "Hennessey Performance Engineering",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Hispanos Suiza": {
      "brand": "Hispanos Suiza",
      "marketEntity": "Hispano Suiza Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Honda": {
      "brand": "Honda",
      "marketEntity": "Honda Motor Co., Ltd.",
      "displayTicker": "HMC",
      "quoteSymbol": "HMC",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 27.71,
      "change": 1.23,
      "changePercent": 4.645,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:11:24+00:00",
      "status": "ok"
    },
    "Jaguar": {
      "brand": "Jaguar",
      "marketEntity": "Tata Motors Limited",
      "displayTicker": "TATAMOTORS.NS",
      "quoteSymbol": "TATAMOTORS.BSE",
      "exchange": "India",
      "currency": "INR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Jaguar",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "no_quote"
    },
    "Koenigsegg": {
      "brand": "Koenigsegg",
      "marketEntity": "Koenigsegg Automotive AB",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Laffite": {
      "brand": "Laffite",
      "marketEntity": "Laffite Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Lamborghini": {
      "brand": "Lamborghini",
      "marketEntity": "Volkswagen AG",
      "displayTicker": "VOW3.DE",
      "quoteSymbol": "VOW3.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: grupo controlador da Lamborghini",
      "price": 89.32,
      "change": -1.7,
      "changePercent": -1.8677,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:11:56+00:00",
      "status": "ok"
    },
    "Lexus": {
      "brand": "Lexus",
      "marketEntity": "Toyota Motor Corporation",
      "displayTicker": "TM",
      "quoteSymbol": "TM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Lexus",
      "price": 180.22,
      "change": -0.27,
      "changePercent": -0.1496,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:13:32+00:00",
      "status": "ok"
    },
    "Lotus": {
      "brand": "Lotus",
      "marketEntity": "Lotus Technology Inc.",
      "displayTicker": "LOT",
      "quoteSymbol": "LOT",
      "exchange": "NASDAQ",
      "currency": "USD",
      "relationType": "proxy_affiliated",
      "relationLabel": "Proxy: empresa listada associada à marca Lotus",
      "price": 1.3,
      "change": -0.02,
      "changePercent": -1.5152,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:13:45+00:00",
      "status": "ok"
    },
    "Lykan": {
      "brand": "Lykan",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Maserati": {
      "brand": "Maserati",
      "marketEntity": "Stellantis N.V.",
      "displayTicker": "STLA",
      "quoteSymbol": "STLA",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Maserati",
      "price": 7.35,
      "change": -0.33,
      "changePercent": -4.2969,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:13:58+00:00",
      "status": "ok"
    },
    "McLaren": {
      "brand": "McLaren",
      "marketEntity": "McLaren Group Holdings",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Mercedes-AMG": {
      "brand": "Mercedes-AMG",
      "marketEntity": "Mercedes-Benz Group AG",
      "displayTicker": "MBG.DE",
      "quoteSymbol": "MBG.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Mercedes-AMG",
      "price": 49.955,
      "change": -1.715,
      "changePercent": -3.3191,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:14:11+00:00",
      "status": "ok"
    },
    "Mercedes-Benz": {
      "brand": "Mercedes-Benz",
      "marketEntity": "Mercedes-Benz Group AG",
      "displayTicker": "MBG.DE",
      "quoteSymbol": "MBG.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 49.955,
      "change": -1.715,
      "changePercent": -3.3191,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:14:11+00:00",
      "status": "ok"
    },
    "Mosler": {
      "brand": "Mosler",
      "marketEntity": "Mosler Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Sem cotação pública direta confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "NIO": {
      "brand": "NIO",
      "marketEntity": "NIO Inc.",
      "displayTicker": "NIO",
      "quoteSymbol": "NIO",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 5.75,
      "change": -0.26,
      "changePercent": -4.3261,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:14:24+00:00",
      "status": "ok"
    },
    "Naran": {
      "brand": "Naran",
      "marketEntity": "Naran Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Nilu27": {
      "brand": "Nilu27",
      "marketEntity": "Nilu27",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Nissan": {
      "brand": "Nissan",
      "marketEntity": "Nissan Motor Co., Ltd.",
      "displayTicker": "NSANY",
      "quoteSymbol": "NSANY",
      "exchange": "OTC/ADR",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação ADR da fabricante",
      "price": 4.48,
      "change": -0.172,
      "changePercent": -3.6973,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:14:38+00:00",
      "status": "ok"
    },
    "Noble": {
      "brand": "Noble",
      "marketEntity": "Noble Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Pagani": {
      "brand": "Pagani",
      "marketEntity": "Pagani Automobili",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Pininfarina": {
      "brand": "Pininfarina",
      "marketEntity": "Mahindra & Mahindra Ltd.",
      "displayTicker": "M&M.NS",
      "quoteSymbol": "M&M.BSE",
      "exchange": "India",
      "currency": "INR",
      "relationType": "proxy_parent",
      "relationLabel": "Proxy: controladora da Pininfarina",
      "price": 3010.95,
      "change": 12.25,
      "changePercent": 0.4085,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:14:54+00:00",
      "status": "ok"
    },
    "Porsche": {
      "brand": "Porsche",
      "marketEntity": "Porsche AG",
      "displayTicker": "P911.DE",
      "quoteSymbol": "P911.DEX",
      "exchange": "Xetra",
      "currency": "EUR",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 47.58,
      "change": -0.31,
      "changePercent": -0.6473,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:12:26+00:00",
      "status": "ok"
    },
    "Praga": {
      "brand": "Praga",
      "marketEntity": "Praga Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Red Bull": {
      "brand": "Red Bull",
      "marketEntity": "Red Bull GmbH",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Rimac": {
      "brand": "Rimac",
      "marketEntity": "Rimac Group",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Rodin": {
      "brand": "Rodin",
      "marketEntity": "Rodin Cars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "SCG": {
      "brand": "SCG",
      "marketEntity": "Scuderia Cameron Glickenhaus",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "SSC": {
      "brand": "SSC",
      "marketEntity": "SSC North America",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Saleen": {
      "brand": "Saleen",
      "marketEntity": "Saleen Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Sem cotação pública direta confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Spyker": {
      "brand": "Spyker",
      "marketEntity": "Spyker",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "unavailable",
      "relationLabel": "Sem indicador de mercado confiável",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "TVR": {
      "brand": "TVR",
      "marketEntity": "TVR",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Toyota": {
      "brand": "Toyota",
      "marketEntity": "Toyota Motor Corporation",
      "displayTicker": "TM",
      "quoteSymbol": "TM",
      "exchange": "NYSE",
      "currency": "USD",
      "relationType": "direct",
      "relationLabel": "Cotação direta da fabricante",
      "price": 180.22,
      "change": -0.27,
      "changePercent": -0.1496,
      "latestTradingDay": "2026-06-03",
      "lastUpdated": "2026-06-04T00:13:32+00:00",
      "status": "ok"
    },
    "Tushek": {
      "brand": "Tushek",
      "marketEntity": "Tushek & Spigel Supercars",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Ultima": {
      "brand": "Ultima",
      "marketEntity": "Ultima Sports",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Vector": {
      "brand": "Vector",
      "marketEntity": "Vector Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "W Motors": {
      "brand": "W Motors",
      "marketEntity": "W Motors",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    },
    "Zenvo": {
      "brand": "Zenvo",
      "marketEntity": "Zenvo Automotive",
      "displayTicker": "",
      "quoteSymbol": "",
      "exchange": "",
      "currency": "",
      "relationType": "private",
      "relationLabel": "Empresa privada, sem cotação pública direta",
      "price": null,
      "change": null,
      "changePercent": null,
      "latestTradingDay": "",
      "lastUpdated": "",
      "status": "not_listed"
    }
  }
};
